### ISSUE TITLE
H1 header displays two underlines simultaneously

### ISSUE THREAD

**Issue by delisma** [cds-snc/gc-articles#1875]
In the WordPress editor of GC-Articles, the H1 header currently displays two underlines simultaneously. One underline is from the GCWeb 2010 version, and the other is from the GCWeb 2023 version. This causes a visual inconsistency in the editor.

## Steps to Reproduce

1. Open the WordPress editor in GC-Articles.
2. Navigate to All Articles
3. Add Article
4. Observe the two underlines under the H1 text.

## Proposed Solution

To resolve this issue, the underline from the GCWeb 2010 version can be removed by deleting the following line in the editor CSS:
https://github.com/cds-snc/gc-articles/blob/be763a4ef10dd3085a0844adb13b9cde16813cc1/wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor.css#L41

## Screenshot
![image](https://github.com/user-attachments/assets/af55ea14-7553-4cf1-a693-2ce019eb3cd3)

**Comment by patheard** [comment]
This has now been deployed and tested in Staging and is working as expected:
![image](https://github.com/user-attachments/assets/e76aa5b7-0640-498a-bbd0-3bb9c2f43a70)

I'll get it deployed to Prod once I finish going through the regression tests.

**Comment by patheard** [comment]
This is now fixed in prod as well - thanks for the bug report!
![image](https://github.com/user-attachments/assets/3a943ec0-cc6f-4f20-9d59-834c76ec6740)
